qbittorrent_user: "your_qbittorrent_user"
qbittorrent_pass: "your_qbittorrent_pass"
qbittorrent_port: 8080  # optional, defaults to 8080
qbittorrent_server: "localhost"  # optional, defaults to 'localhost'
gluetun_server: "localhost"  # optional, defaults to 'localhost'
gluetun_port: 8000  # optional, defaults to 8000
update_freq: 600  # optional, defaults to 600
